name: ${project.name}
main: de.themoep.interserverports.InterServerPorts
version: '${minecraft.plugin.version}'
description: ${project.description}
authors: [Phoenix616]
commands:
   InterServerPorts:
      aliases: [isp]
      description: Command description.
      usage: /<command> reload
      permission: InterServerPorts.command
      permission-message: You don't have the permission <permission>
permissions:
   InterServerPorts.command:
      description: Gives permission to the plugin command
      default: op