name: ${project.name}
main: de.themoep.interserverports.InterServerPorts
version: '${minecraft.plugin.version}'
description: ${project.description}
authors: [Phoenix616]
commands:
   BukkitTemplatePlugin:
      aliases: [btp]
      description: Command description.
      usage: /<command>
      permission: InterServerPorts.command
      permission-message: You don't have the permission <permission>
permissions:
   BukkitTemplatePlugin.command:
      description: Gives permission to the plugin command
      default: op